### ISSUE TITLE
Bug: Import of files not working: Uncaught TypeError: Cannot read properties of undefined (reading 'val')

### ISSUE THREAD

**Issue by LordofAgents** [mattwright324/maps-let-loose#63]
Hey, I am not able to import exported maps from the tool.
There is no visible error message, but the console logs the following message:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'val')
    at HTMLInputElement.<anonymous> (script.js?v=2022-12-14T17:11:16+00:00:3024:41)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```
Full log on the console:
![image](https://user-images.githubusercontent.com/52619285/210084458-9a97eaea-57a0-4791-a458-b113ce5a772b.png)

I tested this issue in chrome and firefox on Windows 11.
Thank you for this amazing tool, and for your work in it!

**Comment by mattwright324** [comment]
Hi @LordofAgents 

There does appear to be an issue on import, thanks!

The issue appears to be related to import using the import button in the page. However, in the mean time you can still import by drag-and-dropping the exported zip file into the page instead of using the file chooser popup linked to the button. This method does not have the issue.

**Comment by mattwright324** [comment]
Importing using the button is now fixed

**Comment by LordofAgents** [comment]
Thank you, amazing!
