### ISSUE TITLE
Rooms functionality broken on mattw.io

### ISSUE THREAD

**Issue by joobei** [mattwright324/maps-let-loose#91]
First of all: Awesome work on the tool :) Big kudos ^_^
The rooms functionality doesn't seem to work. I suppose you're aware?

![image](https://user-images.githubusercontent.com/2638631/232415143-bd5f8735-21c3-4892-8bb5-5f353eea5f78.png)

**Comment by mattwright324** [comment]
Hi @joobei 

Thanks! I was not aware it was down as I wasn't awake. I'm not exactly sure what happened but based off logs/metrics it seems that potentially there was some kind of connection spam. I seem to be able to connect without issue this morning. Unsure if was happened was intentional but hopefully it doesn't happen again

**Comment by joobei** [comment]
It has never worked for me. Just tried it now. Could it be related to firefox ad blocking add-ons?

**Comment by mattwright324** [comment]
Interesting, I use FireFox and uBlock and haven't had issues. What country/region are you located and what blocking addons are you using? Any errors in the F12 browser console?

**Comment by mattwright324** [comment]
Are you accessing the page directly or embedded in some other way?

**Comment by joobei** [comment]
@mattwright324 big apologies for not responding on a timely manner. I missed the email. I was accessing the page directly.
